title: Joanna Lamch
name: Joanna Lamch
author: Joanna Lamch
email: jlamch@gmail.com
description: Software development; software gardener; development passionate;

baseurl: "" #"jlamch.net" # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: "" #http://localhost:4000/ #the url of your site 

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/wordcloud_transparent.png

project_one: WebAssembly and .NET
project_one_description: some description
project_one_url: https://github.com/jlamch/WebAssemblyAndDotNet
project_one_icon: location_on

project_two: Just a bit about DevOps on VSTS
project_two_description: some description
#project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: webassembly_language_white_with_fiolet.png


# project_three: Third Project
# project_three_description: Describe your project!
# project_three_url: https://github.com/jameshamann/jekyll-material-theme
# project_three_icon: hotel


# project_four: Fourth Project
# project_four_description: Describe your project!
# project_four_url: https://github.com/jameshamann/jekyll-material-theme
# project_four_icon: restaurant

portfolio_heading: Speaker
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: visualstudio
  - name: csharp
  - name: dot-net
  - name: typescript
  - name: android
  - name: apple
  #- name: chrome
  #- name: confluence
  - name: docker
  #- name: amazonwebservices
  - name: bitbucket
  - name: git
  - name: github
  - name: gitlab
  - name: slack
  #- name: photoshop
  #- name: sourcetree
  - name: dot-net
  - name: csharp
  - name: visualstudio

  #- name: ssh
  #- name: angularjs
  #- name: apache
  #- name: appcelerator
  #- name: atom
  #- name: babel
  #- name: backbonejs
  #- name: bootstrap
  #- name: bower
  #- name: c
  #- name: codeigniter
  #- name: coffescript
  #- name: cplusplus
  #- name: css3
  #- name: cucumber
  #- name: d3js
  #- name: debian
  #- name: devicon
  #- name: django
  #- name: doctrine
  #- name: drupal
  #- name: erlang
  #- name: facebook
  #- name: firefox
  #- name: foundation
  #- name: gatling
  #- name: gimp
  #- name: go
  #- name: google
  #- name: gradle
  #- name: grunt
  #- name: gulp
  #- name: heroku
  #- name: html5
  #- name: ie10
  #- name: illustrator
  #- name: inkscape
  #- name: itellij
  #- name: java
  #- name: jasmine
  #- name: javascript
  #- name: laravel
  #- name: less
  #- name: linux
  #- name: meteor
  #- name: mocha
  #- name: mongodb
  #- name: moodle
  #- name: mysql
  #- name: nginx
  #- name: nodejs
  #- name: nodewebkit
  #- name: oracle
  #- name: php
  #- name: phpstorm
  #- name: protractor
  #- name: postgresql
  #- name: python
  #- name: pycharm
  #- name: rails
  #- name: react
  #- name: redhat
  #- name: redis
  #- name: ruby
  #- name: rubymine
  #- name: safari
  #- name: sass
  #- name: sequelize
  #- name: swift
  #- name: symfony
  #- name: tomcat
  #- name: travis
  #- name: trello
  #- name: twitter
  #- name: ubuntu
  #- name: vim
  #- name: vuejs
  #- name: webpack
  #- name: webstorm
  #- name: windows8
  #- name: wordpress
  #- name: yii
  #- name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joannalamch/  
  - title: github
    url: https://github.com/jlamch
  - title: twitter
    url: https://twitter.com/JLamch
  - title: meetup
    url: https://www.meetup.com/Śląska-Grupa-Microsoft-Meetup  

github: https://github.com/jlamch
medium: https://medium.com
linkedin: https://www.linkedin.com/in/joannalamch/

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-127059285-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
